#!/bin/sh

yarn: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -	&& \
	  echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list	&&	\
	  sudo apt update && sudo apt install yarn
	  
install: curl -L http://www.gi-harmony.com/download/crypto-web/crypto-web-application_v0.0.0.2.tar.gz | tar xz && yarn install
