#!/bin/sh

yarn: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      @echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list	&&	\
      sudo apt update && sudo apt install yarn

git-clone:
	@echo "Initialization Clone Crypto Dashboard Project" && git clone git@github.com:naruemont/CryptoDashboard.git && mv ./CryptoDashboard/* . && rm -R CryptoDashboard

credentials: 
	test -f ~/.ssh/id_rsa || (				\
	read -p "Please Enter Your Email:" email;	\
	ssh-keygen -t rsa -b 4096 -C $$email);)
	eval `ssh-agent` && ssh-add ~/.ssh/id_rsa
	@echo "Please Add SSH key to your github account:" && cat ~/.ssh/id_rsa.pub
	  
install: $(MAKE) yarn git-clone
	 yarn install
	 @echo "Finished Installation"
	 

start: 
	nohup yarn start && echo "Crypto Dashboard is running" &

stop:
	kill -9 $(shell lsof -i TCP:$(port) | grep LISTEN | awk '{print $$2}') && echo "Crypto Dashboard has been stopped"
