#!/bin/sh

git-clone:
	@echo "Initialization Clone Deversifi Middleware API Project" && git clone --branch v0.0.1-deversifi_middleware_api git@github.com:noppakao/Deversifi_Middleware_API.git && mv ./Deversifi_Middleware_API/* . && rm -R Deversifi_Middleware_API

credentials: 
	test -f ~/.ssh/id_rsa || (				\
	read -p "Please Enter Your Email:" email;	\
	ssh-keygen -t rsa -b 4096 -C $$email);)
	eval `ssh-agent` && ssh-add ~/.ssh/id_rsa
	@echo "Please Add SSH key to your github account:" && cat ~/.ssh/id_rsa.pub


	
install:
	$(MAKE) git-clone
	sudo apt install npm && sudo npm install
	@echo "Finished Installation"

start: 
	nohup node server.js && echo "Deversifi Middleware API start listenning on port 3001" &

stop:
	kill -9 $(shell lsof -i TCP:3001 | grep LISTEN | awk '{print $$2}') && echo "Deversifi Middleware API has been stopped"

	

