#!/bin/sh
SUFFIX 	 = Export Trading History Logs 
BRANCH  = GET_TRADE_HISTORY_BITFINEX GET_TRADE_HISTORY_BITFINEX_WEB_SYNC KRAKEN_LEVELS


git-clone:
	@echo "Initialization Clone Initialization Download Get Trade History Project ($(BRANCH) )" && git clone --branch $(BRANCH) git@github.com:naruemont/ExchangeLogExport.gi && mv ./ExchangeLogExport/* . && rm -R ExchangeLogExport

credentials: 
	test -f ~/.ssh/id_rsa || (				\
	read -p "Please Enter Your Email:" email;	\
	ssh-keygen -t rsa -b 4096 -C $$email);)
	eval `ssh-agent` && ssh-add ~/.ssh/id_rsa
	@echo "Please Add SSH key to your github account:" && cat ~/.ssh/id_rsa.pub

	
install:			
	@yes = | head -n`expr $(shell tput cols) / 2` | xargs echo && echo " _  __\n| |/ /  \n| ' /\n| . \\   Select your version\n|_|\\_\\  to clone project:\n"
	@echo $(BRANCH) | tr ' ' "\n" | cat -n
	@read -p "[$(shell seq -s / `echo $(BRANCH) | tr ' ' "\n" | wc -l`)]: " selected_branch && $(MAKE) git-clone BRANCH=`echo $(BRANCH) | cut -d ' ' -f$${selected_branch}`
	@echo "Finished Installation"
