#!/bin/sh


install:
	@echo "Initialization Download Get Trade History Bitfinex" 
	@read -p "Please Enter Your Personel Token:" TOKEN;	\
	curl -L https://raw.githubusercontent.com/naruemont/ExchangeLogExport/master/GET_TRADE_HISTORY_BITFINEX/GET_TRADE_HISTORY_BITFINEX.tar.gz?token=$$TOKEN | tar xz && chmod +x *
	@echo "Finished Installation"
